### ISSUE TITLE
French translation

### ISSUE THREAD

**Issue by Ekaekale** [Moppler/Critterpedia#24]
Hey, I did translate all the site including fishs and bugs but the section "locations" is hard-coded in English so I can't do anything for it and don't know how to do ahah.  =)
![image](https://user-images.githubusercontent.com/60019130/79039382-2eb9ad80-7be1-11ea-9204-59499f54331e.png)

**Comment by Moppler** [comment]
This has been patched in version 1.8.1. Please feel free to correct the translations if the current ones aren't accurate enough.
